# Dataset and DataLoader Class in PyTorch

In [13]:
from sklearn.datasets import make_classification
import torch

In [14]:
# Step 1 create a synthetic classification dataset using scikit-learn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [15]:
X.shape, X

((10, 2),
 array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]))

In [16]:
y.shape, y

((10,), array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [17]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [18]:
X, y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [28]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [23]:
# create a class custom dataset
class CustomDataset(TensorDataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [25]:
dataset = CustomDataset(X, y)

In [26]:
len(dataset)

10

In [27]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [37]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [49]:
for batch_features, batch_labels in dataloader:
    print(f'Features: {batch_features}')
    print(f'Labels: {batch_labels}')
    print('-'*50)

Features: tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
Labels: tensor([1, 0])
--------------------------------------------------
Features: tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
Labels: tensor([0, 0])
--------------------------------------------------
Features: tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
Labels: tensor([0, 1])
--------------------------------------------------
Features: tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
Labels: tensor([1, 1])
--------------------------------------------------
Features: tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
Labels: tensor([1, 0])
--------------------------------------------------
